# -*- coding: utf-8 -*-
"""DEPLOYMENT NOTEBOOK(no training , final UI/UX).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TA7UCP0Oyvg2DYdRIcNVgquZA_RoAeN2
"""

#IMPORTS
!pip install stable-baselines3

import numpy as np
import pandas as pd

import pickle
from tensorflow.keras.models import load_model
from stable_baselines3 import PPO

#LOAD ALL MODELS
# Load Layer 1
rf = pickle.load(open("rf_final.pkl", "rb"))
xgb_model = pickle.load(open("xgb_final.pkl", "rb"))
meta_model = pickle.load(open("meta_final.pkl", "rb"))
scaler = pickle.load(open("scaler_final.pkl", "rb"))

# Load Layer 2
autoencoder = load_model("autoencoder_final.h5")

# Load threshold
threshold = np.load("threshold_final.npy")

# Load Layer 3
model = PPO.load("rl_model_final")

print("✅ All models loaded successfully")

#LOAD DATA
df = pd.read_csv("/content/drive/MyDrive/ Cyber breach prediction,detection & isolation using ML/MachineLearningCVE/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv")

df.columns = df.columns.str.strip()

# Drop label if present
if "Label" in df.columns:
    df = df.drop("Label", axis=1)

# Replace infinity withWorking NaN
df.replace([np.inf, -np.inf], np.nan, inplace=True)
# Fill NaN values with 0
df.fillna(0, inplace=True)

X = df.values

#CORE PREDICTION FUNCTION
def predict_single(sample):

    # Scale input
    sample = scaler.transform(sample.reshape(1, -1))

    # 🔷 Layer 1 (Prediction)
    rf_p = rf.predict_proba(sample)
    xgb_p = xgb_model.predict_proba(sample)

    stack = np.hstack((rf_p, xgb_p))
    pred = meta_model.predict(stack)[0]

    # 🔷 Layer 2 (Autoencoder)
    recon = autoencoder.predict(sample, verbose=0)
    mse_val = np.mean((sample - recon)**2)

    if mse_val > threshold * 3:
        sev = 2
    elif mse_val > threshold:
        sev = 1
    else:
        sev = 0

    # 🔷 Layer 3 (RL Decision)
    state = np.array([[pred, mse_val, sev]], dtype=np.float32)
    action, _ = model.predict(state, deterministic=True)

    action_map = {
        0: "ALLOW",
        1: "MONITOR",
        2: "BLOCK",
        3: "ISOLATE"
    }

    return action_map[action.item()]

#BATCH PREDICTION
# 🔷 Scale entire dataset
X_scaled = scaler.transform(X)

# 🔷 Layer 1
rf_probs = rf.predict_proba(X_scaled)
xgb_probs = xgb_model.predict_proba(X_scaled)

stack = np.hstack((rf_probs, xgb_probs))
preds = meta_model.predict(stack)

# 🔷 Layer 2
recon = autoencoder.predict(X_scaled, verbose=0)
mse = np.mean((X_scaled - recon)**2, axis=1)

# 🔷 Severity
severity = np.where(mse > threshold*3, 2,
            np.where(mse > threshold, 1, 0))

# 🔷 RL states
states = np.column_stack((preds, mse, severity)).astype(np.float32)

# 🔷 RL prediction
actions, _ = model.predict(states, deterministic=True)

# 🔷 Map actions
action_map = {
    0: "ALLOW",
    1: "MONITOR",
    2: "BLOCK",
    3: "ISOLATE"
}

results = [action_map[a] for a in actions]

# 🔷 Output
print(pd.Series(results).value_counts())

#SAVE RESULTS
output_df = pd.DataFrame({
    "Action": results
})

output_df.to_csv("deployment_results.csv", index=False)

print("✅ Results saved")

#REAL-TIME DEMO
import time

print("=== Live Detection ===")

for i in range(10):
    action = predict_single(X[i])
    print(f"Sample {i} → {action}")
    time.sleep(1)

!pip install streamlit

import streamlit as st

st.title("Cyber IDS System")

uploaded_file = st.file_uploader("Upload CSV")

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    X = df.values

    results = [predict_single(x) for x in X]

    st.write(pd.Series(results).value_counts())

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# 
# st.title("Cyber IDS System")
# 
# uploaded_file = st.file_uploader("Upload CSV")
# 
# if uploaded_file:
#     df = pd.read_csv(uploaded_file)
#     X = df.values
# 
#     # Assuming predict_single is defined in the notebook context
#     # and can be accessed from the Streamlit script's environment.
#     # If predict_single is not globally available in the script's scope,
#     # it would need to be imported or defined within app.py.
#     # For this example, we'll assume it's accessible.
#     # If it causes an error, we might need to redefine/import it here.
# 
#     # To make predict_single available within the streamlit app.py context,
#     # we need to ensure its dependencies (rf, xgb_model, meta_model, scaler,
#     # autoencoder, threshold, model) are also loaded or passed.
#     # For simplicity, we'll assume they are globally accessible if this were run from colab itself.
#     # A more robust solution would be to load them inside app.py or pass them.
# 
#     # Let's add a placeholder for now, as the actual predict_single requires models loaded in colab session.
#     # If you run app.py independently, these models need to be loaded within app.py
# 
#     # Since the previous cells have loaded all the models and defined predict_single,
#     # the following line will try to use the function from the global scope.
#     # In a typical streamlit deployment, you would load these models inside app.py
#     # However, for colab execution, this setup might work due to shared global scope.
#     try:
#         results = [predict_single(x) for x in X]
#         st.write(pd.Series(results).value_counts())
#     except NameError:
#         st.error("The `predict_single` function or its dependencies are not defined in the Streamlit script's scope. Please ensure all models and functions are loaded/defined within `app.py` for standalone execution.")

# The 'localtunnel' package is typically installed via npm, not pip.
# The subsequent 'npx localtunnel' command will handle the installation if needed.

!streamlit run app.py & npx localtunnel --port 8501

